ControleDeParcerias/ControleDeParcerias.Web - Copia/ViewModels/ParceriaViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ControleDeParcerias.Web.ViewModels
{
    public class ParceriaViewModel
    {
        public ParceriaViewModel()
        {
            DataHoraCadastro = DateTime.Now;
        }
        [Key]
        [Display(Name = "Cód. Parceria")]
        public int Codigo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo Titulo é obrigatório", AllowEmptyStrings = false)]
        [Display(Name = "Título")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo Descrição é obrigatório", AllowEmptyStrings = false)]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        [Display(Name = "URL da pagina")]
        public string URLPagina { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo Empresa é obrigatório", AllowEmptyStrings = false)]
        [Display(Name = "Empresa")]
        public string Empresa { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo Data Inicio é obrigatório", AllowEmptyStrings = false)]
        [Display(Name = "Data Início")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        [DataType(DataType.Date, ErrorMessage = "Data em formato inválido")]
        public DateTime DataInicio { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo Data Termino é obrigatório", AllowEmptyStrings = false)]
        [Display(Name = "Data Término")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        [DataType(DataType.Date, ErrorMessage = "Data em formato inválido")]
        public DateTime DataTermino { get; set; }

        [Display(Name = "Qtd. Likes")]
        public int QtdLikes { get; set; }
        public DateTime DataHoraCadastro { get; set; } = DateTime.Now;
    }
}

ControleDeParcerias/ControleDeParcerias.Web - Copia/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeParcerias.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ControleDeParcerias/ControleDeParcerias.Web - Copia/Controllers/ParceriaController.cs
using ControleDeParcerias.Data.Interfaces.Servicos;
using ControleDeParcerias.Web.Mappers;
using ControleDeParcerias.Web.ViewModels;
using ControleParcerias.Dominio.Entidades;
using System;
using System.Net;
using System.Web.Mvc;

namespace ControleDeParcerias.Web.Controllers
{
    public class ParceriaController : Controller
    {
        private readonly IParceriaService _parceriaService;
        private readonly ParceriaMapperProfile _parceriaMapperProfile;

        public ParceriaController(IParceriaService parceriaService)
        {
            _parceriaService = parceriaService;
            _parceriaMapperProfile = new ParceriaMapperProfile();
        }

        public ActionResult Index()
        {
            return View(_parceriaMapperProfile.EntityToViewModel(_parceriaService.GetTodos()));
        }

        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParceriaViewModel parceriaViewModel = _parceriaMapperProfile.MapperConfig.Map<Parceria, ParceriaViewModel>(_parceriaService.GetPorId(id));
            if (parceriaViewModel == null)
            {
                return HttpNotFound();
            }
            return View(parceriaViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Codigo,Titulo,Descricao,URLPagina,Empresa,DataInicio,DataTermino,QtdLikes,DataHoraCadastro")] ParceriaViewModel parceriaViewModel)
        {
            parceriaViewModel.DataHoraCadastro = DateTime.Now;
            if (ModelState.IsValid)
            {
                _parceriaService.Adicionar(_parceriaMapperProfile.MapperConfig.Map<ParceriaViewModel, Parceria>(parceriaViewModel));
                return RedirectToAction("Index");
            }

            return View(parceriaViewModel);
        }

        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParceriaViewModel parceriaViewModel = _parceriaMapperProfile.MapperConfig.Map<Parceria, ParceriaViewModel>(_parceriaService.GetPorId(id));
            if (parceriaViewModel == null)
            {
                return HttpNotFound();
            }
            return View(parceriaViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Codigo,Titulo,Descricao,URLPagina,Empresa,DataInicio,DataTermino,QtdLikes,DataHoraCadastro")] ParceriaViewModel parceriaViewModel)
        {
            if (ModelState.IsValid)
            {
                _parceriaService.Atualizar(_parceriaMapperProfile.MapperConfig.Map<ParceriaViewModel, Parceria>(parceriaViewModel));
                return RedirectToAction("Index");
            }
            return View(parceriaViewModel);
        }

        public ActionResult DeleteConfirmed(int id)
        {
            _parceriaService.Deletar(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public bool BuscarTituloParceria(string titulo)
        {
            return _parceriaService.VerificarNomeTitulo(titulo);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _parceriaService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ControleDeParcerias/ControleDeParcerias.Web - Copia/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ControleDeParcerias/ControleDeParcerias.Web - Copia/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ControleDeParcerias/ControleDeParcerias.Web - Copia/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ControleDeParcerias/ControleDeParcerias.Web - Copia/Views/Parceria/Create.cshtml
@model ControleDeParcerias.Web.ViewModels.ParceriaViewModel

@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadastro</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Parceria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                <br />
                <span id="error-Titulo" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URLPagina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URLPagina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URLPagina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataTermino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataTermino, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataTermino, "", new { @class = "text-danger" })
                <br />
                <span id="error-dataTermino" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QtdLikes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtdLikes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtdLikes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="btn_salvar_parceria" type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#DataTermino").keyup(function () {
            var DataInicio = $("#DataInicio").val();
            var DataTermino = $("#DataTermino").val();

            let partsDataInicio = DataInicio.split('-');
            let partsDataTermino = DataTermino.split('-');

            var dataInicial = new Date(partsDataInicio[0], partsDataInicio[1] - 1, partsDataInicio[2]);
            var dataFinal = new Date(partsDataTermino[0], partsDataTermino[1] - 1, partsDataTermino[2]);

            if (dataInicial < dataFinal) {
                debugger;

                var timeDiff = dataFinal.getTime() - dataInicial.getTime();
                const DAY = 24 * 60 * 60 * 1000;
                var diffDays = timeDiff / DAY;

                if (diffDays < 5) {
                    $("#error-dataTermino").text("A Data de Termino deve ter uma diferença de 5 dias ou mais da Data Inicial")
                    $("#btn_salvar_parceria").css('display', 'none');
                } else {
                    $("#error-dataTermino").text("")
                    $("#btn_salvar_parceria").css('display', '');
                }
            } else {
                $("#error-dataTermino").text("A Data de Termino deve ser maior que a Data Inicial")
                $("#btn_salvar_parceria").css('display', 'none');
            }
        });

        $("#Titulo").keyup(function () {
            $.ajax({
                type: "GET",
                traditional: true,
                url: '@Url.Action("BuscarTituloParceria", "Parceria")',
                data: { titulo: $("#Titulo").val()},
                success: function (data) {
                    if (data == "True") {
                        $("#error-Titulo").text("O tituto ja está cadastrado, digite outro titulo")
                        $("#btn_salvar_parceria").css('display', 'none');
                    } else {
                        $("#error-Titulo").text("")
                        $("#btn_salvar_parceria").css('display', '');
                    }
                },
                error: function () {
                    alert("Erro na tentativa de emissão!");
                }
    });
        });

    </script>
}

ControleDeParcerias/ControleDeParcerias.Web - Copia/Views/Parceria/Delete.cshtml
@model ControleDeParcerias.Web.ViewModels.ParceriaViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ParceriaViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URLPagina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URLPagina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataTermino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataTermino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtdLikes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtdLikes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataHoraCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataHoraCadastro)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ControleDeParcerias/ControleDeParcerias.Web - Copia/Views/Parceria/Edit.cshtml
@model ControleDeParcerias.Web.ViewModels.ParceriaViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edição</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Parceria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Codigo)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                <br />
                <span id="error-Titulo" class="text-danger"></span>
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URLPagina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URLPagina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URLPagina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataTermino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataTermino, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataTermino, "", new { @class = "text-danger" })
                <br />
                <span id="error-dataTermino" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QtdLikes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtdLikes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtdLikes, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="btn_salvar_parceria" type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#DataTermino").keyup(function () {
            var DataInicio = $("#DataInicio").val();
            var DataTermino = $("#DataTermino").val();

            let partsDataInicio = DataInicio.split('-');
            let partsDataTermino = DataTermino.split('-');

            var dataInicial = new Date(partsDataInicio[0], partsDataInicio[1] - 1, partsDataInicio[2]);
            var dataFinal = new Date(partsDataTermino[0], partsDataTermino[1] - 1, partsDataTermino[2]);

            if (dataInicial < dataFinal) {
                debugger;

                var timeDiff = dataFinal.getTime() - dataInicial.getTime();
                const DAY = 24 * 60 * 60 * 1000;
                var diffDays = timeDiff / DAY;

                if (diffDays < 5) {
                    $("#error-dataTermino").text("A Data de Termino deve ter uma diferença de 5 dias ou mais da Data Inicial")
                    $("#btn_salvar_parceria").css('display', 'none');
                } else {
                    $("#error-dataTermino").text("")
                    $("#btn_salvar_parceria").css('display', '');
                }
            } else {
                $("#error-dataTermino").text("A Data de Termino deve ser maior que a Data Inicial")
                $("#btn_salvar_parceria").css('display', 'none');
            }
        });

        $("#Titulo").keyup(function () {
            $.ajax({
                type: "GET",
                traditional: true,
                url: '@Url.Action("BuscarTituloParceria", "Parceria")',
                data: { titulo: $("#Titulo").val()},
                success: function (data) {
                    if (data == "True") {
                        $("#error-Titulo").text("O tituto ja está cadastrado, digite outro titulo")
                        $("#btn_salvar_parceria").css('display', 'none');
                    } else {
                        $("#error-Titulo").text("")
                        $("#btn_salvar_parceria").css('display', '');
                    }
                },
                error: function () {
                    alert("Erro na tentativa de emissão!");
                }
    });
        });

    </script>
}

ControleDeParcerias/ControleDeParcerias.Web - Copia/Views/Parceria/Index.cshtml
@model IEnumerable<ControleDeParcerias.Web.ViewModels.ParceriaViewModel>

@{
    ViewBag.Title = "Index";
}
<div style="padding-top:10px; padding-bottom:10px; padding-left:90%">
    <a href='@Url.Action("Create", "Parceria")' class="btn btn-default" role="button" aria-pressed="true">Cadastrar</a>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Empresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataTermino)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QtdLikes)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empresa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataTermino)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QtdLikes)
            </td>
            <td>
                @Html.ActionLink("Alterar", "Edit", new { id = item.Codigo }) |
                @Html.ActionLink("Detalhe", "Details", new { id = item.Codigo }) |
                <a href="javascript:CarregarURL(@item.Codigo)">Delete</a>

                @*@Html.ActionLink("Excluir", "Delete", new { id = item.Codigo , data-toggle = "modal",  })*@

                <!-- Button trigger modal -->
                @*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalDelete">
                    Launch demo modal
                </button>*@
            </td>
        </tr>
    }

</table>

<!-- Modal -->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                @*<h5 class="modal-title" id="exampleModalLabel">Modal title</h5>*@
                <a href="javascript:FecharModal()" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </a>
            </div>
            <div class="modal-body">
                Deseja realmente excluir essa parceria?
            </div>
            <span id="valorDeId" class="hidden">@Url.Action("DeleteConfirmed", "Parceria")</span>
            <div class="modal-footer">
                <a href="" id="btnDeletar" type="button" class="btn btn-default">Sim</a>
                <a href="javascript:FecharModal()" type="button" class="btn btn-secondary" data-dismiss="modal">Não</a>
            </div>
        </div>
    </div>
</div>

<script>
    function CarregarURL(id) {
        var primeiraParte = $("#valorDeId").text(); 
        var URLFinal = primeiraParte + "/" + id
        $("#btnDeletar").attr("href", URLFinal)
        $("#modalDelete").attr("class", "modal fade in");
        $("#modalDelete").css('display', 'block');
    }

    function FecharModal() {
        $("#modalDelete").attr("class", "modal fade");
        $("#modalDelete").css('display', 'none');
    }
</script>

ControleDeParcerias/ControleDeParcerias.Web - Copia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Parcerias", "Index", "Parceria", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>